// Language dictionary for the Effect Builder
// This file is loaded before main.js

window.translations = {
    en: {
        translation: {
            "nav": {
                "new": "New",
                "open": "Open",
                "save": "Save",
                "share": "Share",
                "export": "Export",
                "import": "Import to SignalRGB",
                "gallery": "Community Gallery",
                "showcase": "Effect Showcase",
                "builder": "Component Builder",
                "signin": "Sign In",
                "signout": "Sign Out",
                "help": "Help",
                "about": "About",
                "report": "Report Bug",
                "theme": "Change Theme"
            },
            "controls": {
                "title": "Controls",
                "addObject": "Add Object",
                "addPolyline": "Add Polyline",
                "objectDefaultName": "Object",
                "lock": "Lock Object",
                "unlock": "Unlock Object",
                "duplicate": "Duplicate",
                "delete": "Delete"
            },
            "gallery": {
                "title": "Community Gallery",
                "backToEditor": "Back to Editor",
                "description": "Browse public effects created with the SRGB Interactive Effect Builder.",
                "intro": "Browse public effects created by the community. Click the \"Load\" button on any effect to open it in the editor.",
                "allEffects": "All Effects",
                "myFavoriteEffects": "My Favorite Effects",
                "sortBy": "Sort By:",
                "newest": "Newest",
                "mostLiked": "Most Liked",
                "mostDownloaded": "Most Downloaded",
                "alphabetical": "Alphabetical",
                "load": "Load",
                "like": "Like",
                "liked": "Liked",
                "unlike": "Unlike",
                "by": "By",
                "anonymous": "Anonymous",
                "noDescription": "No description provided.",
                "edit": "Edit",
                "feature": "Feature",
                "unfeature": "Un-feature",
                "regenThumb": "Regen Thumb",
                "deleteConfirm": "Are you sure you want to delete \"{{name}}\"? This cannot be undone.",
                "failedDelete": "Failed to delete project.",
                "endOfResults": "End of results.",
                "noEffectsFound": "No effects found.",
                "modalTitle": "Edit Effect Details",
                "effectName": "Effect Name",
                "effectDescription": "Description",
                "cancel": "Cancel",
                "saveChanges": "Save Changes",
                "saving": "Saving...",
                "views": "Views",
                "downloads": "Downloads",
                "likes": "Likes",
                "loginToLike": "You must be logged in to like or unlike an effect."
            },
            "properties": {
                "Shape": "Shape",
                "X Position": "X Position",
                "Y Position": "Y Position",
                "Width": "Width",
                "Height": "Height",
                "Rotation": "Rotation",
                "Fill Shape": "Fill Shape",
                "Fill Type": "Fill Type",
                "Gradient Colors": "Gradient Colors",
                "Use Sharp Gradient": "Use Sharp Gradient",
                "Animation Mode": "Animation Mode",
                "Animation Speed": "Animation Speed",
                "Cycle Colors": "Cycle Colors",
                "Color Cycle Speed": "Color Cycle Speed",
                "Rotation Speed": "Rotation Speed",
                "Scroll Direction": "Scroll Direction",
                "Phase Offset": "Phase Offset",
                "Text": "Text",
                "Font Size": "Font Size",
                "Justification": "Justification",
                "Pixel Font Style": "Pixel Font Style",
                "Text Animation": "Text Animation",
                "Text Scroll Speed": "Text Scroll Speed",
                "Show Current Time": "Show Current Time",
                "Show Current Date": "Show Current Date",
                "Auto-Width": "Auto-Width",
                "Enable Sound Reactivity": "Enable Sound Reactivity",
                "Reactive Property": "Reactive Property",
                "Audio Metric": "Audio Metric",
                "Beat Threshold": "Beat Threshold",
                "Sensitivity": "Sensitivity",
                "Smoothing": "Smoothing",
                "Inner Diameter": "Inner Diameter",
                "Segments": "Segments",
                "Segment Angle": "Segment Angle",
                "General Settings": "General Settings",
                "Number of Rows": "Number of Rows",
                "Number of Columns": "Number of Columns",
                "Line Width": "Line Width",
                "Wave Type": "Wave Type",
                "Frequency": "Frequency",
                "Display Mode": "Display Mode",
                "Pulse Depth": "Pulse Depth",
                "Enable Wave Animation": "Enable Wave Animation",
                "Wave Style": "Wave Style",
                "Wave Count": "Wave Count",
                "Spread": "Spread",
                "Pixel Art Data": "Pixel Art Data",
                "Layout": "Layout",
                "Draw Style": "Draw Style",
                "Visualizer Style": "Visualizer Style",
                "Auto Scale": "Auto Scale",
                "Max Bar Height": "Max Bar Height",
                "Bar Count": "Bar Count",
                "Bar Spacing": "Bar Spacing",
                "Use Segments": "Use Segments",
                "Segment Count": "Segment Count",
                "Segment Spacing": "Segment Spacing",
                "Bass Level": "Bass Level",
                "Treble Boost": "Treble Boost",
                "Dynamic Range": "Dynamic Range",
                "Sensor Target": "Sensor Target",
                "User Sensor": "User Sensor",
                "Line Thickness": "Line Thickness",
                "Fill Area": "Fill Area",
                "Show Value": "Show Value",
                "Time Scale": "Time Scale",
                "Color Mode": "Color Mode",
                "Mid Threshold": "Mid Threshold",
                "Max Threshold": "Max Threshold",
                "Block Count": "Block Count",
                "Block Size": "Block Size",
                "Direction": "Direction",
                "Easing": "Easing",
                "Block Spacing": "Block Spacing",
                "Glitch Frequency": "Glitch Frequency",
                "Pulse Speed": "Pulse Speed",
                "Snake Direction": "Snake Direction",
                "Count": "Count",
                "Spawn Rate": "Spawn Rate",
                "Lifetime": "Lifetime",
                "Speed": "Speed",
                "Speed Variance": "Speed Variance",
                "Gravity": "Gravity",
                "Size": "Size",
                "Size Randomness": "Size Randomness",
                "Rotation Variance": "Rotation Variance",
                "Initial Rotation Random": "Initial Rotation Random",
                "Matrix Char Set": "Matrix Char Set",
                "Trail Length": "Trail Length",
                "Enable Glow": "Enable Glow",
                "Glow Size": "Glow Size",
                "Glow Color": "Glow Color",
                "SVG Path": "SVG Path",
                "Enable Trail": "Enable Trail",
                "Trail Spacing": "Trail Spacing",
                "GIF URL": "GIF URL",
                "Fit Mode": "Fit Mode",
                "Filter": "Filter",
                "Filter Value": "Filter Value"
            },
            "values": {
                "Rectangle": "Rectangle",
                "Circle": "Circle",
                "Ring": "Ring",
                "Polygon": "Polygon",
                "Star": "Star",
                "Text": "Text",
                "Oscilloscope": "Oscilloscope",
                "Tetris": "Tetris",
                "Fire": "Fire",
                "Fire Radial": "Fire Radial",
                "Pixel Art": "Pixel Art",
                "Audio Visualizer": "Audio Visualizer",
                "Spawner": "Spawner",
                "Strimer": "Strimer",
                "Polyline": "Polyline",
                "Gif": "Gif",
                "Solid": "Solid",
                "Linear": "Linear",
                "Radial": "Radial",
                "Conic": "Conic",
                "Alternating": "Alternating",
                "Random": "Random",
                "Rainbow": "Rainbow",
                "Rainbow Radial": "Rainbow Radial",
                "Rainbow Conic": "Rainbow Conic",
                "Cycle All Blocks": "Cycle All Blocks",
                "None": "None",
                "Loop": "Loop",
                "Bounce": "Bounce",
                "Bounce Reversed": "Bounce Reversed",
                "Bounce Random": "Bounce Random",
                "Right": "Right",
                "Left": "Left",
                "Up": "Up",
                "Down": "Down",
                "Small": "Small",
                "Large": "Large",
                "Center": "Center",
                "Marquee": "Marquee",
                "Typewriter": "Typewriter",
                "Wave": "Wave",
                "Flash": "Flash",
                "Volume Meter": "Volume Meter",
                "Volume": "Volume",
                "Bass": "Bass",
                "Mids": "Mids",
                "Highs": "Highs",
                "Sine": "Sine",
                "Square": "Square",
                "Sawtooth": "Sawtooth",
                "Triangle": "Triangle",
                "Line": "Line",
                "Points": "Points",
                "Both": "Both",
                "Bars": "Bars",
                "Area": "Area",
                "Circular": "Circular",
                "Sensor Meter": "Sensor Meter",
                "Time Plot": "Time Plot",
                "Cpu Load": "CPU Load",
                "Gpu Load": "GPU Load",
                "Ram Load": "RAM Load",
                "Net Down": "Net Down",
                "Net Up": "Net Up",
                "Contain": "Contain",
                "Cover": "Cover",
                "Fill": "Fill",
                "Grayscale": "Grayscale",
                "Sepia": "Sepia",
                "Invert": "Invert",
                "Blur": "Blur",
                "Brightness": "Brightness",
                "Contrast": "Contrast",
                "Hue Rotate": "Hue Rotate",
                "Saturate": "Saturate"
            }
        }
    },
    es: {
        translation: {
             "nav": {
                "new": "Nuevo",
                "open": "Abrir",
                "save": "Guardar",
                "share": "Compartir",
                "export": "Exportar",
                "import": "Importar a SignalRGB",
                "gallery": "Galería",
                "showcase": "Escaparate",
                "builder": "Constructor",
                "signin": "Entrar",
                "signout": "Salir",
                 "help": "Ayuda",
                "about": "Acerca de",
                "report": "Reportar Error",
                "theme": "Tema"
            },
            "controls": {
                "title": "Controles",
                "addObject": "Añadir Objeto",
                "addPolyline": "Añadir Polilínea",
                "objectDefaultName": "Objeto",
                "lock": "Bloquear Objeto",
                "unlock": "Desbloquear Objeto",
                "duplicate": "Duplicar",
                "delete": "Eliminar"
            },
            "gallery": {
                "title": "Galería de la Comunidad",
                "backToEditor": "Volver al Editor",
                "description": "Explora efectos públicos creados con el SRGB Interactive Effect Builder.",
                "intro": "Explora efectos públicos creados por la comunidad. Haz clic en el botón \"Cargar\" en cualquier efecto para abrirlo en el editor.",
                "allEffects": "Todos los Efectos",
                "myFavoriteEffects": "Mis Favoritos",
                "sortBy": "Ordenar por:",
                "newest": "Más Recientes",
                "mostLiked": "Más Gustados",
                "mostDownloaded": "Más Descargados",
                "alphabetical": "Alfabético",
                "load": "Cargar",
                "like": "Me Gusta",
                "liked": "Me Gusta",
                "unlike": "Ya no me gusta",
                "by": "Por",
                "anonymous": "Anónimo",
                "noDescription": "Sin descripción.",
                "edit": "Editar",
                "feature": "Destacar",
                "unfeature": "No Destacar",
                "regenThumb": "Regen. Miniatura",
                "deleteConfirm": "¿Estás seguro de que quieres eliminar \"{{name}}\"? Esto no se puede deshacer.",
                "failedDelete": "Error al eliminar el proyecto.",
                "endOfResults": "Fin de los resultados.",
                "noEffectsFound": "No se encontraron efectos.",
                "modalTitle": "Editar Detalles del Efecto",
                "effectName": "Nombre del Efecto",
                "effectDescription": "Descripción",
                "cancel": "Cancelar",
                "saveChanges": "Guardar Cambios",
                "saving": "Guardando...",
                "views": "Vistas",
                "downloads": "Descargas",
                "likes": "Me Gusta",
                "loginToLike": "Debes iniciar sesión para dar me gusta."
            },
             "properties": {
                "Shape": "Forma",
                "X Position": "Posición X",
                "Y Position": "Posición Y",
                "Width": "Ancho",
                "Height": "Alto",
                "Rotation": "Rotación",
                "Fill Shape": "Rellenar Forma",
                "Fill Type": "Tipo de Relleno",
                "Gradient Colors": "Colores del Gradiente",
                "Use Sharp Gradient": "Usar Gradiente Nítido",
                "Animation Mode": "Modo de Animación",
                "Animation Speed": "Velocidad de Animación",
                "Cycle Colors": "Ciclar Colores",
                "Color Cycle Speed": "Velocidad de Ciclo",
                "Rotation Speed": "Velocidad de Rotación",
                "Scroll Direction": "Dirección",
                "Phase Offset": "Desfase",
                "Text": "Texto",
                "Font Size": "Tamaño de Fuente",
                "Justification": "Justificación",
                "Pixel Font Style": "Estilo de Fuente",
                "Text Animation": "Animación de Texto",
                "Text Scroll Speed": "Velocidad de Texto",
                "Show Current Time": "Mostrar Hora",
                "Show Current Date": "Mostrar Fecha",
                "Auto-Width": "Ancho Automático",
                "Enable Sound Reactivity": "Reactividad al Sonido",
                "Reactive Property": "Propiedad Reactiva",
                "Audio Metric": "Métrica de Audio",
                "Beat Threshold": "Umbral de Ritmo",
                "Sensitivity": "Sensibilidad",
                "Smoothing": "Suavizado",
                "Inner Diameter": "Diámetro Interno",
                "Segments": "Segmentos",
                "Segment Angle": "Ángulo de Segmento",
                "General Settings": "Configuración General",
                "Number of Rows": "Filas",
                "Number of Columns": "Columnas",
                "Line Width": "Ancho de Línea",
                "Wave Type": "Tipo de Onda",
                "Frequency": "Frecuencia",
                "Display Mode": "Modo de Visualización",
                "Pulse Depth": "Profundidad de Pulso",
                "Enable Wave Animation": "Animar Onda",
                "Wave Style": "Estilo de Onda",
                "Wave Count": "Conteo de Ondas",
                "Spread": "Propagación",
                "Pixel Art Data": "Datos de Pixel Art",
                "Layout": "Diseño",
                "Draw Style": "Estilo de Dibujo",
                "Visualizer Style": "Estilo de Visualizador",
                "Auto Scale": "Escala Automática",
                "Max Bar Height": "Altura Máxima de Barra",
                "Bar Count": "Conteo de Barras",
                "Bar Spacing": "Espaciado de Barras",
                "Use Segments": "Usar Segmentos",
                "Segment Count": "Conteo de Segmentos",
                "Segment Spacing": "Espaciado de Segmentos",
                "Bass Level": "Nivel de Bajos",
                "Treble Boost": "Refuerzo de Agudos",
                "Dynamic Range": "Rango Dinámico",
                "Sensor Target": "Objetivo del Sensor",
                "User Sensor": "Sensor de Usuario",
                "Line Thickness": "Grosor de Línea",
                "Fill Area": "Rellenar Área",
                "Show Value": "Mostrar Valor",
                "Time Scale": "Escala de Tiempo",
                "Color Mode": "Modo de Color",
                "Mid Threshold": "Umbral Medio",
                "Max Threshold": "Umbral Máximo",
                "Block Count": "Conteo de Bloques",
                "Block Size": "Tamaño de Bloque",
                "Direction": "Dirección",
                "Easing": "Suavizado",
                "Block Spacing": "Espaciado de Bloques",
                "Glitch Frequency": "Frecuencia de Glitch",
                "Pulse Speed": "Velocidad de Pulso",
                "Snake Direction": "Dirección de Serpiente",
                "Count": "Conteo",
                "Spawn Rate": "Tasa de Generación",
                "Lifetime": "Vida Útil",
                "Speed": "Velocidad",
                "Speed Variance": "Varianza de Velocidad",
                "Gravity": "Gravedad",
                "Size": "Tamaño",
                "Size Randomness": "Aleatoriedad de Tamaño",
                "Rotation Variance": "Varianza de Rotación",
                "Initial Rotation Random": "Rotación Inicial Aleatoria",
                "Matrix Char Set": "Conjunto de Caracteres Matrix",
                "Trail Length": "Longitud de Estela",
                "Enable Glow": "Habilitar Resplandor",
                "Glow Size": "Tamaño de Resplandor",
                "Glow Color": "Color de Resplandor",
                "SVG Path": "Ruta SVG",
                "Enable Trail": "Habilitar Estela",
                "Trail Spacing": "Espaciado de Estela",
                "GIF URL": "URL del GIF",
                "Fit Mode": "Modo de Ajuste",
                "Filter": "Filtro",
                "Filter Value": "Valor de Filtro"
            },
             "values": {
                "Rectangle": "Rectángulo",
                "Circle": "Círculo",
                "Ring": "Anillo",
                "Polygon": "Polígono",
                "Star": "Estrella",
                "Text": "Texto",
                "Oscilloscope": "Osciloscopio",
                "Tetris": "Tetris",
                "Fire": "Fuego",
                "Fire Radial": "Fuego Radial",
                "Pixel Art": "Pixel Art",
                "Audio Visualizer": "Visualizador de Audio",
                "Spawner": "Generador",
                "Strimer": "Strimer",
                "Polyline": "Polilínea",
                "Gif": "Gif",
                "Solid": "Sólido",
                "Linear": "Lineal",
                "Radial": "Radial",
                "Conic": "Cónico",
                "Alternating": "Alterno",
                "Random": "Aleatorio",
                "Rainbow": "Arcoíris",
                "Rainbow Radial": "Arcoíris Radial",
                "Rainbow Conic": "Arcoíris Cónico",
                "Cycle All Blocks": "Ciclar Todos los Bloques",
                "None": "Ninguno",
                "Loop": "Bucle",
                "Bounce": "Rebote",
                "Bounce Reversed": "Rebote Inverso",
                "Bounce Random": "Rebote Aleatorio",
                "Right": "Derecha",
                "Left": "Izquierda",
                "Up": "Arriba",
                "Down": "Abajo",
                "Small": "Pequeño",
                "Large": "Grande",
                "Center": "Centro",
                "Marquee": "Marquesina",
                "Typewriter": "Máquina de Escribir",
                "Wave": "Onda",
                "Flash": "Destello",
                "Volume Meter": "Medidor de Volumen",
                "Volume": "Volumen",
                "Bass": "Bajos",
                "Mids": "Medios",
                "Highs": "Agudos",
                "Sine": "Seno",
                "Square": "Cuadrada",
                "Sawtooth": "Diente de Sierra",
                "Triangle": "Triángulo",
                "Line": "Línea",
                "Points": "Puntos",
                "Both": "Ambos",
                "Bars": "Barras",
                "Area": "Área",
                "Circular": "Circular",
                "Sensor Meter": "Medidor de Sensor",
                "Time Plot": "Gráfico de Tiempo",
                "Cpu Load": "Carga de CPU",
                "Gpu Load": "Carga de GPU",
                "Ram Load": "Carga de RAM",
                "Net Down": "Descarga de Red",
                "Net Up": "Subida de Red",
                "Contain": "Contener",
                "Cover": "Cubrir",
                "Fill": "Rellenar",
                "Grayscale": "Escala de Grises",
                "Sepia": "Sepia",
                "Invert": "Invertir",
                "Blur": "Desenfocar",
                "Brightness": "Brillo",
                "Contrast": "Contraste",
                "Hue Rotate": "Rotar Matiz",
                "Saturate": "Saturar"
            }
        }
    }
};
