// Language dictionary for the Effect Builder
// This file is loaded before main.js

window.translations = {
    en: {
        translation: {
            "nav": {
                "new": "New",
                "open": "Open",
                "save": "Save",
                "share": "Share",
                "export": "Export",
                "import": "Import to SignalRGB",
                "gallery": "Community Gallery",
                "showcase": "Effect Showcase",
                "builder": "Component Builder",
                "signin": "Sign In",
                "signout": "Sign Out",
                "help": "Help",
                "about": "About",
                "report": "Report Bug",
                "theme": "Change Theme"
            },
            "controls": {
                "title": "Controls",
                "addObject": "Add Object",
                "addPolyline": "Add Polyline",
                "objectDefaultName": "Object",
                "lock": "Lock Object",
                "unlock": "Unlock Object",
                "duplicate": "Duplicate",
                "delete": "Delete"
            },
            "groups": {
                "Geometry": "Geometry",
                "Polyline": "Polyline",
                "Stroke": "Stroke",
                "Object": "Object",
                "Object Fill": "Object Fill",
                "Fill-Animation": "Fill & Animation",
                "Text": "Text",
                "Oscilloscope": "Oscilloscope",
                "Tetris": "Tetris",
                "Fire": "Fire",
                "Pixel Art": "Pixel Art",
                "Visualizer": "Visualizer",
                "Audio Responsiveness": "Audio Responsiveness",
                "Sensor Responsiveness": "Sensor Responsiveness",
                "Strimer": "Strimer",
                "Spawner": "Spawner",
                "Particle": "Particle",
                "GIF Settings": "GIF Settings"
            },
            "toolbar": {
                "undo": "Undo (Ctrl+Z)",
                "redo": "Redo (Ctrl+Y)",
                "copyProps": "Copy Properties",
                "pasteProps": "Paste Properties",
                "alignLeft": "Align Left to Screen",
                "alignHCenter": "Align Horizontal Center to Screen",
                "alignRight": "Align Right to Screen",
                "alignTop": "Align Top to Screen",
                "alignVCenter": "Align Vertical Center to Screen",
                "alignBottom": "Align Bottom to Screen",
                "matchWidth": "Match Width of First Selected",
                "matchHeight": "Match Height of First Selected",
                "matchSize": "Match Size of First Selected",
                "fitCanvas": "Fit to Canvas",
                "snapCanvas": "Snap to Canvas",
                "matchText": "Match Text Size to Cell Height",
                "startListening": "Start Listening",
                "listening": "Listening...",
                "pasteLayout": "Paste Layout Screenshot",
                "toggleOverlay": "Toggle Overlay",
                "deleteOverlay": "Delete Layout Screenshot",
                "overlayOpacity": "Overlay Opacity",
                "like": "Like"
            },
            "toasts": {
                "success": "Success",
                "error": "Error",
                "notification": "Notification",
                "loginRequired": "You must be logged in to like or unlike an effect.",
                "actionFailed": "Could not process like/unlike action.",
                "colorPickerHint": "Double-click to open color picker",
                "signInToLoad": "Please sign in to load effects.",
                "effectNotFound": "The associated effect was not found.",
                "loadFailed": "Failed to load the effect.",
                "gifReadError": "Could not read GIF properties.",
                "giphyKeyMissing": "Giphy API key is not configured.",
                "gifUrlApplied": "GIF URL applied!",
                "gifFetchFailed": "Failed to fetch the selected GIF.",
                "giphySearchFailed": "Giphy search failed. Check your API key and network connection.",
                "regenThumb": "Regenerating thumbnail...",
                "regenThumbSuccess": "Thumbnail regenerated and saved successfully! This tab will now close.",
                "regenThumbFailed": "Failed to save new thumbnail.",
                "htmlCopied": "HTML code copied to clipboard!",
                "copyFailed": "Could not copy code. See console for details.",
                "zipStarted": "Zip file download started.",
                "exportFailed": "Failed to export file: {{error}}",
                "gifNoPreprocess": "Error: GIF data was not pre-processed.",
                "gifNoFrames": "Could not extract frames from GIF.",
                "gifNoPalette": "Could not find a valid color palette in this GIF.",
                "gifProcessed": "{{count}} GIF frames processed with {{colors}} colors!",
                "gifProcessFailed": "Could not process GIF file. It may be corrupt or in an unsupported format.",
                "noImagePaste": "No image was prepared for pasting. Please copy the image again.",
                "noTargetObject": "Error: No target object was specified for pasting.",
                "frameDimsPositive": "Frame dimensions must be positive numbers.",
                "spriteProcessed": "{{frames}} frame(s) processed with {{colors}} colors!",
                "spritePasteFailed": "Could not paste sprite: {{error}}",
                "pixelsShifted": "Shifted pixels in all {{count}} frames!",
                "noClipboardImage": "No image found on clipboard.",
                "clipboardReadFailed": "Could not read image from clipboard.",
                "frameDuplicated": "Frame duplicated!",
                "deleteLastFrame": "Cannot delete the last frame.",
                "frameDeleted": "Frame deleted!",
                "gradientMinColors": "A gradient must have at least 2 colors.",
                "colorInUse": "Cannot delete a color that is in use in one or more animation frames.",
                "saveBeforeLike": "Please save your effect to the cloud before liking it.",
                "featuredUpdated": "Featured effect updated successfully!",
                "featuredUpdateFailed": "Failed to update featured status.",
                "signInToViewLikers": "You must be signed in to view likers.",
                "projectNotFound": "Project not found.",
                "noLikers": "No users have liked \"{{name}}\" yet.",
                "likersFetchFailed": "Failed to retrieve the list of likers.",
                "workspaceCreated": "New workspace created.",
                "loadMoreFailed": "Could not load more effects.",
                "configProcessFailed": "Failed to process configuration.",
                "invalidWorkspace": "Invalid workspace data provided.",
                "workspaceLoadFailed": "Failed to load workspace.",
                "polylineMinNodes": "A polyline must have at least 2 nodes.",
                "pixelArtMinFrames": "Pixel Art object must have at least one frame.",
                "polylineTooFew": "Polyline creation failed (too few nodes).",
                "polylineCreated": "Polyline created!",
                "signInToSave": "You must be logged in to save.",
                "projectOverwritten": "Project \"{{name}}\" was overwritten successfully!",
                "overwriteFailed": "Error overwriting project: {{error}}",
                "projectSaved": "Effect \"{{name}}\" was saved successfully!",
                "saveFailed": "Error saving project: {{error}}",
                "signInToSeeProjects": "You must be logged in to see your projects.",
                "layoutPasted": "Layout image pasted and saved!",
                "layoutTooLarge": "Image loaded (too large to save).",
                "layoutDeleted": "Layout screenshot deleted.",
                "signInToShare": "You must be logged in to share.",
                "shareLinkUpdated": "Effect \"{{name}}\" updated and share link generated!",
                "shareLinkCreated": "New effect \"{{name}}\" saved and share link copied!",
                "shareFailed": "Could not share effect: {{error}}",
                "sharedLoaded": "Shared effect loaded!",
                "notPublic": "This effect is not public.",
                "sharedNotFound": "Shared effect not found.",
                "sharedLoadFailed": "Could not load the shared effect.",
                "fileEmpty": "The provided file or text is empty.",
                "noProperties": "No valid properties were found in the file.",
                "effectLoaded": "Effect loaded successfully!",
                "parseFailed": "Could not parse the provided file. Please check the format.",
                "fileReadError": "Error reading file: {{error}}",
                "saveBeforeSharing": "Please save the effect before sharing.",
                "linkCopied": "Link copied to clipboard!",
                "polylineToolActive": "Polyline tool activated. Click on the canvas to start drawing. Double-click to finish.",
                "propsCopied": "Properties copied!",
                "propsPasted": "Properties pasted to {{count}} object(s).",
                "audioConnected": "Tab audio connected! Your visualizer is now live.",
                "audioFailed": "Tab capture was canceled or failed.",
                "featuredLoaded": "Featured effect \"{{name}}\" loaded!",
                "selectPixelArt": "Please select exactly one pixel art object to insert frames into.",
                "notPixelArt": "The selected object is not a pixel art object.",
                "framesReplaced": "Replaced frames and colors successfully!",
                "insertFailed": "Could not insert frames. Data might be invalid.",
                "selectSinglePixelArt": "Please select a single pixel art object first.",
                "commentsLoadFailed": "Could not load comments.",
                "commentModeration": "Your comment contains a disallowed word. Please revise it.",
                "signInToComment": "You must be logged in to comment.",
                "noEffectSelected": "Cannot post comment: No effect selected.",
                "commentPostFailed": "Could not post your comment.",
                "deletingComment": "Removing comment...",
                "commentDeleted": "Comment deleted.",
                "commentDeleteFailed": "Could not delete comment.",
                "signInForAction": "You must be logged in to perform this action.",
                "markReadFailed": "Could not mark all notifications as read.",
                "signedOut": "Signed out successfully.",
                "signOutFailed": "Error signing out. Please try again."
            },
            "descriptions": {
                "Shape": "The basic shape of the object.",
                "X Position": "The horizontal position of the object on the canvas.",
                "Y Position": "The vertical position of the object on the canvas.",
                "Width": "The width of the object.",
                "Height": "The height of the object.",
                "Rotation": "The static rotation of the object in degrees.",
                "Fill Shape": "Fills the interior of the shape with the selected fill style.",
                "Fill Type": "The type of color fill or gradient to use.",
                "Gradient Colors": "The colors and positions of the gradient.",
                "Use Sharp Gradient": "If checked, creates a hard line between colors.",
                "Animation Mode": "Determines how the gradient animation behaves.",
                "Animation Speed": "Master speed for particle systems, gradient scroll, and other animations.",
                "Cycle Colors": "Animates the colors by cycling through the color spectrum.",
                "Color Cycle Speed": "The speed at which colors cycle.",
                "Rotation Speed": "The continuous rotation speed of the object.",
                "Scroll Direction": "The direction the gradient animation moves.",
                "Phase Offset": "Offsets the gradient animation for each item.",
                "Text": "The text to display.",
                "Font Size": "The size of the text.",
                "Justification": "Text alignment.",
                "Pixel Font Style": "The style of the pixel font.",
                "Text Animation": "The animation style for the text.",
                "Text Scroll Speed": "The speed of the text animation.",
                "Show Current Time": "Displays the current system time.",
                "Show Current Date": "Displays the current system date.",
                "Auto-Width": "Automatically adjusts width to fit text.",
                "Enable Sound Reactivity": "Makes the object react to audio.",
                "Reactive Property": "The property that changes with audio.",
                "Audio Metric": "The part of the audio spectrum to react to.",
                "Beat Threshold": "The volume level required to trigger a reaction.",
                "Sensitivity": "How strongly the object reacts to audio.",
                "Smoothing": "Smooths out the audio reaction.",
                "Inner Diameter": "The size of the hole in the center.",
                "Segments": "The number of segments in the shape.",
                "Segment Angle": "The angle covered by each segment.",
                "General Settings": "Global settings for the effect.",
                "Effect Title": "The name of your effect.",
                "Description": "A short description of your effect.",
                "Publisher": "Your name or handle.",
                "Enable Animation": "Toggles all animations on or off.",
                "Enable Sound": "Enables audio processing for the effect.",
                "Enable Global Color Palette": "Forces all objects to use the global gradient.",
                "Global Gradient": "The master color gradient.",
                "Enable Global Color Cycle": "Forces all objects to cycle colors.",
                "Global Color Cycle Speed": "The speed of the global color cycle."
            },
            "comments": {
                "header": "Comments",
                "publicNotice": "Comments are public. Please be respectful and courteous.",
                "loading": "Loading comments...",
                "savePrompt": "Save this component to the cloud to enable comments.",
                "addComment": "Add a comment",
                "placeholder": "Write your comment...",
                "post": "Post Comment",
                "posting": "Posting...",
                "signinPrompt": "Please sign in to post a comment.",
                "noComments": "No comments yet. Be the first!"
            },
            "gallery": {
                "title": "Community Gallery",
                "backToEditor": "Back to Editor",
                "description": "Browse public effects created with the SRGB Interactive Effect Builder.",
                "intro": "Browse public effects created by the community. Click the \"Load\" button on any effect to open it in the editor.",
                "allEffects": "All Effects",
                "myFavoriteEffects": "My Favorite Effects",
                "sortBy": "Sort By:",
                "newest": "Newest",
                "mostLiked": "Most Liked",
                "mostDownloaded": "Most Downloaded",
                "alphabetical": "Alphabetical",
                "load": "Load",
                "like": "Like",
                "liked": "Liked",
                "unlike": "Unlike",
                "by": "By",
                "anonymous": "Anonymous",
                "noDescription": "No description provided.",
                "edit": "Edit",
                "feature": "Feature",
                "unfeature": "Un-feature",
                "regenThumb": "Regen Thumb",
                "deleteConfirm": "Are you sure you want to delete \"{{name}}\"? This cannot be undone.",
                "failedDelete": "Failed to delete project.",
                "endOfResults": "End of results.",
                "noEffectsFound": "No effects found.",
                "modalTitle": "Edit Effect Details",
                "effectName": "Effect Name",
                "effectDescription": "Description",
                "cancel": "Cancel",
                "saveChanges": "Save Changes",
                "saving": "Saving...",
                "views": "Views",
                "downloads": "Downloads",
                "likes": "Likes",
                "loginToLike": "You must be logged in to like or unlike an effect."
            },
            "properties": {
                "Effect Title": "Effect Title",
                "Description": "Description",
                "Publisher": "Publisher",
                "Enable Animation": "Enable Animation",
                "Enable Sound": "Enable Sound",
                "Enable Global Color Palette": "Enable Global Color Palette",
                "Global Gradient": "Global Gradient",
                "Enable Global Color Cycle": "Enable Global Color Cycle",
                "Global Color Cycle Speed": "Global Color Cycle Speed",
                "Shape": "Shape",
                "X Position": "X Position",
                "Y Position": "Y Position",
                "Width": "Width",
                "Height": "Height",
                "Rotation": "Rotation",
                "Fill Shape": "Fill Shape",
                "Fill Type": "Fill Type",
                "Gradient Colors": "Gradient Colors",
                "Use Sharp Gradient": "Use Sharp Gradient",
                "Animation Mode": "Animation Mode",
                "Animation Speed": "Animation Speed",
                "Cycle Colors": "Cycle Colors",
                "Color Cycle Speed": "Color Cycle Speed",
                "Rotation Speed": "Rotation Speed",
                "Scroll Direction": "Scroll Direction",
                "Phase Offset": "Phase Offset",
                "Text": "Text",
                "Font Size": "Font Size",
                "Justification": "Justification",
                "Pixel Font Style": "Pixel Font Style",
                "Text Animation": "Text Animation",
                "Text Scroll Speed": "Text Scroll Speed",
                "Show Current Time": "Show Current Time",
                "Show Current Date": "Show Current Date",
                "Auto-Width": "Auto-Width",
                "Enable Sound Reactivity": "Enable Sound Reactivity",
                "Reactive Property": "Reactive Property",
                "Audio Metric": "Audio Metric",
                "Beat Threshold": "Beat Threshold",
                "Sensitivity": "Sensitivity",
                "Smoothing": "Smoothing",
                "Inner Diameter": "Inner Diameter",
                "Segments": "Segments",
                "Segment Angle": "Segment Angle",
                "General Settings": "General Settings",
                "Global Overrides": "Global Overrides",
                "Number of Rows": "Number of Rows",
                "Number of Columns": "Number of Columns",
                "Line Width": "Line Width",
                "Wave Type": "Wave Type",
                "Frequency": "Frequency",
                "Display Mode": "Display Mode",
                "Pulse Depth": "Pulse Depth",
                "Enable Wave Animation": "Enable Wave Animation",
                "Wave Style": "Wave Style",
                "Wave Count": "Wave Count",
                "Spread": "Spread",
                "Pixel Art Data": "Pixel Art Data",
                "Layout": "Layout",
                "Draw Style": "Draw Style",
                "Visualizer Style": "Visualizer Style",
                "Auto Scale": "Auto Scale",
                "Max Bar Height": "Max Bar Height",
                "Bar Count": "Bar Count",
                "Bar Spacing": "Bar Spacing",
                "Use Segments": "Use Segments",
                "Segment Count": "Segment Count",
                "Segment Spacing": "Segment Spacing",
                "Bass Level": "Bass Level",
                "Treble Boost": "Treble Boost",
                "Dynamic Range": "Dynamic Range",
                "Sensor Target": "Sensor Target",
                "User Sensor": "User Sensor",
                "Line Thickness": "Line Thickness",
                "Fill Area": "Fill Area",
                "Show Value": "Show Value",
                "Time Scale": "Time Scale",
                "Color Mode": "Color Mode",
                "Mid Threshold": "Mid Threshold",
                "Max Threshold": "Max Threshold",
                "Block Count": "Block Count",
                "Block Size": "Block Size",
                "Direction": "Direction",
                "Easing": "Easing",
                "Block Spacing": "Block Spacing",
                "Glitch Frequency": "Glitch Frequency",
                "Pulse Speed": "Pulse Speed",
                "Snake Direction": "Snake Direction",
                "Count": "Count",
                "Spawn Rate": "Spawn Rate",
                "Lifetime": "Lifetime",
                "Speed": "Speed",
                "Speed Variance": "Speed Variance",
                "Gravity": "Gravity",
                "Size": "Size",
                "Size Randomness": "Size Randomness",
                "Rotation Variance": "Rotation Variance",
                "Initial Rotation Random": "Initial Rotation Random",
                "Matrix Char Set": "Matrix Char Set",
                "Trail Length": "Trail Length",
                "Enable Glow": "Enable Glow",
                "Glow Size": "Glow Size",
                "Glow Color": "Glow Color",
                "SVG Path": "SVG Path",
                "Enable Trail": "Enable Trail",
                "Trail Spacing": "Trail Spacing",
                "GIF URL": "GIF URL",
                "Fit Mode": "Fit Mode",
                "Filter": "Filter",
                "Filter Value": "Filter Value"
            },
            "modals": {
                "loadProject": {
                    "title": "Load Project",
                    "body": "Select a project to load. This will overwrite your current workspace."
                },
                "saveProject": {
                    "title": "Save Project",
                    "nameLabel": "Project Name:",
                    "placeholder": "Enter a name for your project...",
                    "existing": "Existing Projects:",
                    "cancel": "Cancel",
                    "save": "Save Project"
                },
                "notification": {
                    "title": "Success",
                    "ok": "OK"
                },
                "confirmOverwrite": {
                    "title": "Confirm Overwrite",
                    "body": "A project with this name already exists. Do you want to overwrite it?",
                    "cancel": "Cancel",
                    "overwrite": "Overwrite"
                },
                "help": {
                    "title": "How to Use the Effect Builder",
                    "interface": "Interface Overview",
                    "canvas": "The Canvas & Toolbar",
                    "advanced": "Advanced Shapes & Tools",
                    "reactivity": "Audio & Sensor Reactivity",
                    "saving": "Saving, Loading & Exporting",
                    "installing": "Installing Custom Effects in SignalRGB",
                    "gotIt": "Got it!"
                },
                "about": {
                    "title": "About Effect Builder",
                    "version": "Version:",
                    "projectHome": "Project Home:",
                    "viewGithub": "View on GitHub",
                    "termsPrivacy": "Terms & Privacy:",
                    "termsLink": "Terms of Usage",
                    "privacyLink": "Privacy Policy",
                    "credits": "Credits & Inspirations",
                    "developers": "For Developers & Contributors",
                    "close": "Close"
                },
                "terms": {
                    "title": "Terms of Usage",
                    "accept": "I Accept"
                },
                "privacy": {
                    "title": "Privacy Policy",
                    "close": "Close"
                },
                "import": {
                    "title": "Import from Meta Tags",
                    "body": "Paste the full block of <strong>&lt;meta&gt;</strong> tags from an old effect file below. This will overwrite your current workspace.",
                    "cancel": "Cancel",
                    "importBtn": "Import Effect"
                },
                "share": {
                    "title": "Share Your Effect",
                    "body": "Anyone with this link can view and load your effect.",
                    "copy": "Copy"
                },
                "exportOptions": {
                    "title": "Export Properties",
                    "body": "Select which properties will be editable by users in SignalRGB. Unchecked properties will be hardcoded into the effect.",
                    "cancel": "Cancel",
                    "copyCode": "Copy Code",
                    "generateZip": "Generate .zip File",
                    "exposeAll": "Expose All",
                    "hardcodeAll": "Hardcode All",
                    "presets": "Presets:",
                    "presetAnimation": "Animation",
                    "presetColors": "Colors",
                    "presetGeometry": "Geometry",
                    "presetGradients": "Gradients",
                    "presetMinimal": "Minimal (User-Friendly)",
                    "presetStatic": "Static (No Animation)"
                },
                "acceptTerms": {
                    "title": "Terms & Privacy",
                    "body": "By using this tool, you agree to the <a href=\"#\" data-bs-toggle=\"modal\" data-bs-target=\"#terms-modal\" data-bs-dismiss=\"modal\">Terms of Usage</a> and acknowledge our <a href=\"#\" data-bs-toggle=\"modal\" data-bs-target=\"#privacy-policy-modal\" data-bs-dismiss=\"modal\">Privacy Policy</a>.",
                    "accept": "I Accept"
                },
                "copyProps": {
                    "title": "Copy Properties",
                    "body": "Select the property groups you want to copy from the source object.",
                    "cancel": "Cancel",
                    "copyBtn": "Copy to Clipboard",
                    "pos": "Position (X, Y)",
                    "size": "Size (Width, Height)",
                    "rot": "Rotation & Rotation Speed",
                    "fill": "Fill Style (Type, Colors, Gradient)",
                    "anim": "Fill Animation (Mode, Speed, Direction)",
                    "colAnim": "Color Animation (Cycle Colors & Speed)",
                    "shape": "Shape Type",
                    "shapeSpecific": "Shape-Specific Properties"
                },
                "pixelEditor": {
                    "title": "Pixel Art Editor",
                    "width": "Grid Width",
                    "height": "Grid Height",
                    "applySize": "Apply New Size",
                    "tools": "Tools:",
                    "paint": "Paint",
                    "fill": "Fill",
                    "flipH": "Flip Horizontal",
                    "flipV": "Flip Vertical",
                    "selectedFill": "Selected Fill",
                    "rawData": "View Raw Data",
                    "jsonLabel": "JSON Data (Advanced)",
                    "cancel": "Cancel",
                    "apply": "Apply Changes"
                },
                "pasteSprite": {
                    "title": "Paste Sprite Sheet",
                    "body": "Enter the dimensions of a **single frame**. The code will automatically detect the number of rows and columns in the sprite sheet you paste.",
                    "frameWidth": "Single Frame Width",
                    "frameHeight": "Single Frame Height",
                    "downsample": "Downsample to frame dimensions (for hi-res pixel art)",
                    "append": "Append to existing frames (instead of replacing)",
                    "pasteBtn": "Paste from Clipboard"
                },
                "pixelGallery": {
                    "title": "Community Pixel Art",
                    "searchPlaceholder": "Search by effect name or creator..."
                },
                "uploadGif": {
                    "title": "Upload GIF Options",
                    "body": "Specify the target pixel art dimensions for your animation.",
                    "targetWidth": "Target Width",
                    "targetHeight": "Target Height",
                    "maxColors": "Max Colors (2-32)",
                    "reduceText": "Reduces the GIF's palette to the specified number of colors.",
                    "append": "Append to existing frames (instead of replacing)",
                    "originalInfo": "Original GIF Info:",
                    "dims": "Dimensions:",
                    "colors": "Unique Colors:",
                    "process": "..."
                },
                "colorMapper": {
                    "title": "Map Colors",
                    "body": "Assign the most common colors from the first frame to the available slots in your object's palette.",
                    "preview": "First Frame Preview",
                    "assignments": "Color Assignments",
                    "cancel": "Cancel",
                    "process": "Process Image"
                },
                "editColor": {
                    "title": "Edit Color",
                    "done": "Done"
                },
                "selectColor": {
                    "title": "Select Color"
                },
                "gifSearch": {
                    "title": "Search for GIFs",
                    "placeholder": "Search for GIFs...",
                    "search": "Search",
                    "close": "Close"
                }
            },
            "gradientPicker": {
                "color": "Color:",
                "hex": "HEX",
                "position": "Position:",
                "help": "<strong>Add:</strong> Click empty space | <strong>Edit:</strong> Click HEX input or double-click marker | <strong>Delete:</strong> Drag marker down"
            },
            "values": {
                "Rectangle": "Rectangle",
                "Circle": "Circle",
                "Ring": "Ring",
                "Polygon": "Polygon",
                "Star": "Star",
                "Text": "Text",
                "Oscilloscope": "Oscilloscope",
                "Tetris": "Tetris",
                "Fire": "Fire",
                "Fire Radial": "Fire Radial",
                "Pixel Art": "Pixel Art",
                "Audio Visualizer": "Audio Visualizer",
                "Spawner": "Spawner",
                "Strimer": "Strimer",
                "Polyline": "Polyline",
                "Gif": "Gif",
                "Solid": "Solid",
                "Linear": "Linear",
                "Radial": "Radial",
                "Conic": "Conic",
                "Alternating": "Alternating",
                "Random": "Random",
                "Rainbow": "Rainbow",
                "Rainbow Radial": "Rainbow Radial",
                "Rainbow Conic": "Rainbow Conic",
                "Cycle All Blocks": "Cycle All Blocks",
                "None": "None",
                "Loop": "Loop",
                "Bounce": "Bounce",
                "Bounce Reversed": "Bounce Reversed",
                "Bounce Random": "Bounce Random",
                "Right": "Right",
                "Left": "Left",
                "Up": "Up",
                "Down": "Down",
                "Small": "Small",
                "Large": "Large",
                "Center": "Center",
                "Marquee": "Marquee",
                "Typewriter": "Typewriter",
                "Wave": "Wave",
                "Flash": "Flash",
                "Volume Meter": "Volume Meter",
                "Volume": "Volume",
                "Bass": "Bass",
                "Mids": "Mids",
                "Highs": "Highs",
                "Sine": "Sine",
                "Square": "Square",
                "Sawtooth": "Sawtooth",
                "Triangle": "Triangle",
                "Line": "Line",
                "Points": "Points",
                "Both": "Both",
                "Bars": "Bars",
                "Area": "Area",
                "Circular": "Circular",
                "Sensor Meter": "Sensor Meter",
                "Time Plot": "Time Plot",
                "Cpu Load": "CPU Load",
                "Gpu Load": "GPU Load",
                "Ram Load": "RAM Load",
                "Net Down": "Net Down",
                "Net Up": "Net Up",
                "Contain": "Contain",
                "Cover": "Cover",
                "Fill": "Fill",
                "Grayscale": "Grayscale",
                "Sepia": "Sepia",
                "Invert": "Invert",
                "Blur": "Blur",
                "Brightness": "Brightness",
                "Contrast": "Contrast",
                "Hue Rotate": "Hue Rotate",
                "Saturate": "Saturate"
            }
        }
    },
    es: {
        translation: {
             "nav": {
                "new": "Nuevo",
                "open": "Abrir",
                "save": "Guardar",
                "share": "Compartir",
                "export": "Exportar",
                "import": "Importar a SignalRGB",
                "gallery": "Galería",
                "showcase": "Escaparate",
                "builder": "Constructor",
                "signin": "Entrar",
                "signout": "Salir",
                 "help": "Ayuda",
                "about": "Acerca de",
                "report": "Reportar Error",
                "theme": "Tema"
            },
            "controls": {
                "title": "Controles",
                "addObject": "Añadir Objeto",
                "addPolyline": "Añadir Polilínea",
                "objectDefaultName": "Objeto",
                "lock": "Bloquear Objeto",
                "unlock": "Desbloquear Objeto",
                "duplicate": "Duplicar",
                "delete": "Eliminar"
            },
            "groups": {
                "Geometry": "Geometría",
                "Polyline": "Polilínea",
                "Stroke": "Trazo",
                "Object": "Objeto",
                "Object Fill": "Relleno del Objeto",
                "Fill-Animation": "Relleno y Animación",
                "Text": "Texto",
                "Oscilloscope": "Osciloscopio",
                "Tetris": "Tetris",
                "Fire": "Fuego",
                "Pixel Art": "Pixel Art",
                "Visualizer": "Visualizador",
                "Audio Responsiveness": "Reactividad de Audio",
                "Sensor Responsiveness": "Reactividad del Sensor",
                "Strimer": "Strimer",
                "Spawner": "Generador",
                "Particle": "Partícula",
                "GIF Settings": "Ajustes de GIF"
            },
            "toolbar": {
                "undo": "Deshacer (Ctrl+Z)",
                "redo": "Rehacer (Ctrl+Y)",
                "copyProps": "Copiar Propiedades",
                "pasteProps": "Pegar Propiedades",
                "alignLeft": "Alinear Izquierda a Pantalla",
                "alignHCenter": "Alinear Centro Horizontal a Pantalla",
                "alignRight": "Alinear Derecha a Pantalla",
                "alignTop": "Alinear Arriba a Pantalla",
                "alignVCenter": "Alinear Centro Vertical a Pantalla",
                "alignBottom": "Alinear Abajo a Pantalla",
                "matchWidth": "Igualar Ancho del Primero",
                "matchHeight": "Igualar Alto del Primero",
                "matchSize": "Igualar Tamaño del Primero",
                "fitCanvas": "Ajustar al Lienzo",
                "snapCanvas": "Ajustar a la Cuadrícula",
                "matchText": "Igualar Texto a Altura de Celda",
                "startListening": "Empezar a Escuchar",
                "listening": "Escuchando...",
                "pasteLayout": "Pegar Captura de Diseño",
                "toggleOverlay": "Alternar Superposición",
                "deleteOverlay": "Eliminar Captura de Diseño",
                "overlayOpacity": "Opacidad de Superposición",
                "like": "Me Gusta"
            },
            "toasts": {
                "success": "Éxito",
                "error": "Error",
                "notification": "Notificación",
                "loginRequired": "Debes iniciar sesión para dar me gusta.",
                "actionFailed": "No se pudo procesar la acción.",
                "colorPickerHint": "Doble clic para abrir el selector de color",
                "signInToLoad": "Por favor inicia sesión para cargar efectos.",
                "effectNotFound": "El efecto asociado no fue encontrado.",
                "loadFailed": "Error al cargar el efecto.",
                "gifReadError": "No se pudieron leer las propiedades del GIF.",
                "giphyKeyMissing": "La clave API de Giphy no está configurada.",
                "gifUrlApplied": "¡URL del GIF aplicada!",
                "gifFetchFailed": "Error al obtener el GIF seleccionado.",
                "giphySearchFailed": "Búsqueda de Giphy fallida. Verifica tu clave API.",
                "regenThumb": "Regenerando miniatura...",
                "regenThumbSuccess": "¡Miniatura regenerada y guardada! Esta pestaña se cerrará.",
                "regenThumbFailed": "Error al guardar la nueva miniatura.",
                "htmlCopied": "¡Código HTML copiado al portapapeles!",
                "copyFailed": "No se pudo copiar el código. Ver consola.",
                "zipStarted": "Descarga de archivo Zip iniciada.",
                "exportFailed": "Error al exportar archivo: {{error}}",
                "gifNoPreprocess": "Error: Los datos del GIF no fueron preprocesados.",
                "gifNoFrames": "No se pudieron extraer cuadros del GIF.",
                "gifNoPalette": "No se encontró una paleta de colores válida en este GIF.",
                "gifProcessed": "¡{{count}} cuadros procesados con {{colors}} colores!",
                "gifProcessFailed": "No se pudo procesar el archivo GIF. Puede estar corrupto.",
                "noImagePaste": "No se preparó ninguna imagen. Por favor copia la imagen de nuevo.",
                "noTargetObject": "Error: No se especificó un objeto destino.",
                "frameDimsPositive": "Las dimensiones del cuadro deben ser números positivos.",
                "spriteProcessed": "¡{{frames}} cuadro(s) procesados con {{colors}} colores!",
                "spritePasteFailed": "No se pudo pegar el sprite: {{error}}",
                "pixelsShifted": "¡Píxeles desplazados en {{count}} cuadros!",
                "noClipboardImage": "No se encontró imagen en el portapapeles.",
                "clipboardReadFailed": "No se pudo leer la imagen del portapapeles.",
                "frameDuplicated": "¡Cuadro duplicado!",
                "deleteLastFrame": "No se puede eliminar el último cuadro.",
                "frameDeleted": "¡Cuadro eliminado!",
                "gradientMinColors": "Un gradiente debe tener al menos 2 colores.",
                "colorInUse": "No se puede eliminar un color que está en uso.",
                "saveBeforeLike": "Por favor guarda tu efecto antes de dar me gusta.",
                "featuredUpdated": "¡Efecto destacado actualizado con éxito!",
                "featuredUpdateFailed": "Error al actualizar estado destacado.",
                "signInToViewLikers": "Debes iniciar sesión para ver a quién le gusta.",
                "projectNotFound": "Proyecto no encontrado.",
                "noLikers": "A nadie le gusta \"{{name}}\" todavía.",
                "likersFetchFailed": "Error al obtener la lista de me gusta.",
                "workspaceCreated": "Nuevo espacio de trabajo creado.",
                "loadMoreFailed": "No se pudieron cargar más efectos.",
                "configProcessFailed": "Error al procesar la configuración.",
                "invalidWorkspace": "Datos de espacio de trabajo inválidos.",
                "workspaceLoadFailed": "Error al cargar el espacio de trabajo.",
                "polylineMinNodes": "Una polilínea debe tener al menos 2 nodos.",
                "pixelArtMinFrames": "El objeto Pixel Art debe tener al menos un cuadro.",
                "polylineTooFew": "Creación de polilínea fallida (muy pocos nodos).",
                "polylineCreated": "¡Polilínea creada!",
                "signInToSave": "Debes iniciar sesión para guardar.",
                "projectOverwritten": "¡Proyecto \"{{name}}\" sobrescrito con éxito!",
                "overwriteFailed": "Error al sobrescribir proyecto: {{error}}",
                "projectSaved": "¡Efecto \"{{name}}\" guardado con éxito!",
                "saveFailed": "Error al guardar proyecto: {{error}}",
                "signInToSeeProjects": "Debes iniciar sesión para ver tus proyectos.",
                "layoutPasted": "¡Imagen de diseño pegada y guardada!",
                "layoutTooLarge": "Imagen cargada (demasiado grande para guardar).",
                "layoutDeleted": "Captura de diseño eliminada.",
                "signInToShare": "Debes iniciar sesión para compartir.",
                "shareLinkUpdated": "¡Efecto \"{{name}}\" actualizado y enlace generado!",
                "shareLinkCreated": "¡Nuevo efecto \"{{name}}\" guardado y enlace copiado!",
                "shareFailed": "No se pudo compartir el efecto: {{error}}",
                "sharedLoaded": "¡Efecto compartido cargado!",
                "notPublic": "Este efecto no es público.",
                "sharedNotFound": "Efecto compartido no encontrado.",
                "sharedLoadFailed": "No se pudo cargar el efecto compartido.",
                "fileEmpty": "El archivo o texto proporcionado está vacío.",
                "noProperties": "No se encontraron propiedades válidas en el archivo.",
                "effectLoaded": "¡Efecto cargado con éxito!",
                "parseFailed": "No se pudo analizar el archivo. Verifica el formato.",
                "fileReadError": "Error al leer archivo: {{error}}",
                "saveBeforeSharing": "Por favor guarda el efecto antes de compartir.",
                "linkCopied": "¡Enlace copiado al portapapeles!",
                "polylineToolActive": "Herramienta polilínea activada. Clic para dibujar, doble clic para terminar.",
                "propsCopied": "¡Propiedades copiadas!",
                "propsPasted": "Propiedades pegadas en {{count}} objeto(s).",
                "audioConnected": "¡Audio conectado! Tu visualizador está activo.",
                "audioFailed": "La captura de pestaña fue cancelada o falló.",
                "featuredLoaded": "¡Efecto destacado \"{{name}}\" cargado!",
                "selectPixelArt": "Por favor selecciona exactamente un objeto pixel art.",
                "notPixelArt": "El objeto seleccionado no es pixel art.",
                "framesReplaced": "¡Cuadros y colores reemplazados con éxito!",
                "insertFailed": "No se pudieron insertar cuadros. Datos inválidos.",
                "selectSinglePixelArt": "Por favor selecciona un solo objeto pixel art primero.",
                "commentsLoadFailed": "No se pudieron cargar los comentarios.",
                "commentModeration": "Tu comentario contiene una palabra prohibida.",
                "signInToComment": "Debes iniciar sesión para comentar.",
                "noEffectSelected": "No se puede comentar: Ningún efecto seleccionado.",
                "commentPostFailed": "No se pudo publicar tu comentario.",
                "deletingComment": "Eliminando comentario...",
                "commentDeleted": "Comentario eliminado.",
                "commentDeleteFailed": "No se pudo eliminar el comentario.",
                "signInForAction": "Debes iniciar sesión para realizar esta acción.",
                "markReadFailed": "No se pudieron marcar todas como leídas.",
                "signedOut": "Sesión cerrada con éxito.",
                "signOutFailed": "Error al cerrar sesión. Intenta de nuevo."
            },
            "descriptions": {
                "Shape": "La forma básica del objeto.",
                "X Position": "La posición horizontal del objeto.",
                "Y Position": "La posición vertical del objeto.",
                "Width": "El ancho del objeto.",
                "Height": "La altura del objeto.",
                "Rotation": "La rotación estática del objeto en grados.",
                "Fill Shape": "Rellena el interior de la forma.",
                "Fill Type": "El tipo de relleno de color o gradiente.",
                "Gradient Colors": "Los colores y posiciones del gradiente.",
                "Use Sharp Gradient": "Crea una línea dura entre colores.",
                "Animation Mode": "Determina cómo se comporta la animación.",
                "Animation Speed": "Velocidad maestra para animaciones.",
                "Cycle Colors": "Anima los colores ciclando por el espectro.",
                "Color Cycle Speed": "La velocidad del ciclo de color.",
                "Rotation Speed": "La velocidad de rotación continua.",
                "Scroll Direction": "La dirección de la animación.",
                "Phase Offset": "Desplaza la animación para cada ítem.",
                "Text": "El texto a mostrar.",
                "Font Size": "El tamaño del texto.",
                "Justification": "Alineación del texto.",
                "Pixel Font Style": "El estilo de la fuente de píxeles.",
                "Text Animation": "El estilo de animación del texto.",
                "Text Scroll Speed": "La velocidad de la animación de texto.",
                "Show Current Time": "Muestra la hora actual del sistema.",
                "Show Current Date": "Muestra la fecha actual del sistema.",
                "Auto-Width": "Ajusta el ancho automáticamente.",
                "Enable Sound Reactivity": "Hace que el objeto reaccione al audio.",
                "Reactive Property": "La propiedad que cambia con el audio.",
                "Audio Metric": "La parte del espectro de audio a usar.",
                "Beat Threshold": "El nivel de volumen para activar la reacción.",
                "Sensitivity": "Qué tan fuerte reacciona el objeto.",
                "Smoothing": "Suaviza la reacción de audio.",
                "Inner Diameter": "El tamaño del agujero central.",
                "Segments": "El número de segmentos en la forma.",
                "Segment Angle": "El ángulo cubierto por cada segmento.",
                "General Settings": "Configuración global del efecto.",
                "Effect Title": "El nombre de tu efecto.",
                "Description": "Una breve descripción de tu efecto.",
                "Publisher": "Tu nombre o apodo.",
                "Enable Animation": "Alterna todas las animaciones.",
                "Enable Sound": "Habilita el procesamiento de audio.",
                "Enable Global Color Palette": "Fuerza el uso del gradiente global.",
                "Global Gradient": "El gradiente de color maestro.",
                "Enable Global Color Cycle": "Fuerza el ciclo de color global.",
                "Global Color Cycle Speed": "La velocidad del ciclo global."
            },
            "comments": {
                "header": "Comentarios",
                "publicNotice": "Los comentarios son públicos. Por favor, sé respetuoso.",
                "loading": "Cargando comentarios...",
                "savePrompt": "Guarda este componente en la nube para habilitar comentarios.",
                "addComment": "Añadir un comentario",
                "placeholder": "Escribe tu comentario...",
                "post": "Publicar Comentario",
                "posting": "Publicando...",
                "signinPrompt": "Por favor inicia sesión para comentar.",
                "noComments": "Aún no hay comentarios. ¡Sé el primero!"
            },
            "gallery": {
                "title": "Galería de la Comunidad",
                "backToEditor": "Volver al Editor",
                "description": "Explora efectos públicos creados con el SRGB Interactive Effect Builder.",
                "intro": "Explora efectos públicos creados por la comunidad. Haz clic en el botón \"Cargar\" en cualquier efecto para abrirlo en el editor.",
                "allEffects": "Todos los Efectos",
                "myFavoriteEffects": "Mis Favoritos",
                "sortBy": "Ordenar por:",
                "newest": "Más Recientes",
                "mostLiked": "Más Gustados",
                "mostDownloaded": "Más Descargados",
                "alphabetical": "Alfabético",
                "load": "Cargar",
                "like": "Me Gusta",
                "liked": "Me Gusta",
                "unlike": "Ya no me gusta",
                "by": "Por",
                "anonymous": "Anónimo",
                "noDescription": "Sin descripción.",
                "edit": "Editar",
                "feature": "Destacar",
                "unfeature": "No Destacar",
                "regenThumb": "Regen. Miniatura",
                "deleteConfirm": "¿Estás seguro de que quieres eliminar \"{{name}}\"? Esto no se puede deshacer.",
                "failedDelete": "Error al eliminar el proyecto.",
                "endOfResults": "Fin de los resultados.",
                "noEffectsFound": "No se encontraron efectos.",
                "modalTitle": "Editar Detalles del Efecto",
                "effectName": "Nombre del Efecto",
                "effectDescription": "Descripción",
                "cancel": "Cancelar",
                "saveChanges": "Guardar Cambios",
                "saving": "Guardando...",
                "views": "Vistas",
                "downloads": "Descargas",
                "likes": "Me Gusta",
                "loginToLike": "Debes iniciar sesión para dar me gusta."
            },
             "properties": {
                "Effect Title": "Título del Efecto",
                "Description": "Descripción",
                "Publisher": "Publicador",
                "Enable Animation": "Habilitar Animación",
                "Enable Sound": "Habilitar Sonido",
                "Enable Global Color Palette": "Habilitar Paleta de Colores Global",
                "Global Gradient": "Gradiente Global",
                "Enable Global Color Cycle": "Habilitar Ciclo de Color Global",
                "Global Color Cycle Speed": "Velocidad del Ciclo Global",
                "Shape": "Forma",
                "X Position": "Posición X",
                "Y Position": "Posición Y",
                "Width": "Ancho",
                "Height": "Alto",
                "Rotation": "Rotación",
                "Fill Shape": "Rellenar Forma",
                "Fill Type": "Tipo de Relleno",
                "Gradient Colors": "Colores del Gradiente",
                "Use Sharp Gradient": "Usar Gradiente Nítido",
                "Animation Mode": "Modo de Animación",
                "Animation Speed": "Velocidad de Animación",
                "Cycle Colors": "Ciclar Colores",
                "Color Cycle Speed": "Velocidad de Ciclo",
                "Rotation Speed": "Velocidad de Rotación",
                "Scroll Direction": "Dirección",
                "Phase Offset": "Desfase",
                "Text": "Texto",
                "Font Size": "Tamaño de Fuente",
                "Justification": "Justificación",
                "Pixel Font Style": "Estilo de Fuente",
                "Text Animation": "Animación de Texto",
                "Text Scroll Speed": "Velocidad de Texto",
                "Show Current Time": "Mostrar Hora",
                "Show Current Date": "Mostrar Fecha",
                "Auto-Width": "Ancho Automático",
                "Enable Sound Reactivity": "Reactividad al Sonido",
                "Reactive Property": "Propiedad Reactiva",
                "Audio Metric": "Métrica de Audio",
                "Beat Threshold": "Umbral de Ritmo",
                "Sensitivity": "Sensibilidad",
                "Smoothing": "Suavizado",
                "Inner Diameter": "Diámetro Interno",
                "Segments": "Segmentos",
                "Segment Angle": "Ángulo de Segmento",
                "General Settings": "Configuración General",
                "Global Overrides": "Configuración Global",
                "Number of Rows": "Filas",
                "Number of Columns": "Columnas",
                "Line Width": "Ancho de Línea",
                "Wave Type": "Tipo de Onda",
                "Frequency": "Frecuencia",
                "Display Mode": "Modo de Visualización",
                "Pulse Depth": "Profundidad de Pulso",
                "Enable Wave Animation": "Animar Onda",
                "Wave Style": "Estilo de Onda",
                "Wave Count": "Conteo de Ondas",
                "Spread": "Propagación",
                "Pixel Art Data": "Datos de Pixel Art",
                "Layout": "Diseño",
                "Draw Style": "Estilo de Dibujo",
                "Visualizer Style": "Estilo de Visualizador",
                "Auto Scale": "Escala Automática",
                "Max Bar Height": "Altura Máxima de Barra",
                "Bar Count": "Conteo de Barras",
                "Bar Spacing": "Espaciado de Barras",
                "Use Segments": "Usar Segmentos",
                "Segment Count": "Conteo de Segmentos",
                "Segment Spacing": "Espaciado de Segmentos",
                "Bass Level": "Nivel de Bajos",
                "Treble Boost": "Refuerzo de Agudos",
                "Dynamic Range": "Rango Dinámico",
                "Sensor Target": "Objetivo del Sensor",
                "User Sensor": "Sensor de Usuario",
                "Line Thickness": "Grosor de Línea",
                "Fill Area": "Rellenar Área",
                "Show Value": "Mostrar Valor",
                "Time Scale": "Escala de Tiempo",
                "Color Mode": "Modo de Color",
                "Mid Threshold": "Umbral Medio",
                "Max Threshold": "Umbral Máximo",
                "Block Count": "Conteo de Bloques",
                "Block Size": "Tamaño de Bloque",
                "Direction": "Dirección",
                "Easing": "Suavizado",
                "Block Spacing": "Espaciado de Bloques",
                "Glitch Frequency": "Frecuencia de Glitch",
                "Pulse Speed": "Velocidad de Pulso",
                "Snake Direction": "Dirección de Serpiente",
                "Count": "Conteo",
                "Spawn Rate": "Tasa de Generación",
                "Lifetime": "Vida Útil",
                "Speed": "Velocidad",
                "Speed Variance": "Varianza de Velocidad",
                "Gravity": "Gravedad",
                "Size": "Tamaño",
                "Size Randomness": "Aleatoriedad de Tamaño",
                "Rotation Variance": "Varianza de Rotación",
                "Initial Rotation Random": "Rotación Inicial Aleatoria",
                "Matrix Char Set": "Conjunto de Caracteres Matrix",
                "Trail Length": "Longitud de Estela",
                "Enable Glow": "Habilitar Resplandor",
                "Glow Size": "Tamaño de Resplandor",
                "Glow Color": "Color de Resplandor",
                "SVG Path": "Ruta SVG",
                "Enable Trail": "Habilitar Estela",
                "Trail Spacing": "Espaciado de Estela",
                "GIF URL": "URL del GIF",
                "Fit Mode": "Modo de Ajuste",
                "Filter": "Filtro",
                "Filter Value": "Valor de Filtro"
            },
            "modals": {
                "loadProject": {
                    "title": "Cargar Proyecto",
                    "body": "Selecciona un proyecto para cargar. Esto sobrescribirá tu espacio de trabajo actual."
                },
                "saveProject": {
                    "title": "Guardar Proyecto",
                    "nameLabel": "Nombre del Proyecto:",
                    "placeholder": "Introduce un nombre para tu proyecto...",
                    "existing": "Proyectos Existentes:",
                    "cancel": "Cancelar",
                    "save": "Guardar Proyecto"
                },
                "notification": {
                    "title": "Éxito",
                    "ok": "OK"
                },
                "confirmOverwrite": {
                    "title": "Confirmar Sobrescritura",
                    "body": "Ya existe un proyecto con este nombre. ¿Quieres sobrescribirlo?",
                    "cancel": "Cancelar",
                    "overwrite": "Sobrescribir"
                },
                "help": {
                    "title": "Cómo Usar el Constructor de Efectos",
                    "interface": "Resumen de la Interfaz",
                    "canvas": "El Lienzo y Barra de Herramientas",
                    "advanced": "Formas y Herramientas Avanzadas",
                    "reactivity": "Reactividad de Audio y Sensores",
                    "saving": "Guardar, Cargar y Exportar",
                    "installing": "Instalar Efectos Personalizados en SignalRGB",
                    "gotIt": "¡Entendido!"
                },
                "about": {
                    "title": "Acerca del Constructor de Efectos",
                    "version": "Versión:",
                    "projectHome": "Página del Proyecto:",
                    "viewGithub": "Ver en GitHub",
                    "termsPrivacy": "Términos y Privacidad:",
                    "termsLink": "Términos de Uso",
                    "privacyLink": "Política de Privacidad",
                    "credits": "Créditos e Inspiraciones",
                    "developers": "Para Desarrolladores y Colaboradores",
                    "close": "Cerrar"
                },
                "terms": {
                    "title": "Términos de Uso",
                    "accept": "Acepto"
                },
                "privacy": {
                    "title": "Política de Privacidad",
                    "close": "Cerrar"
                },
                "import": {
                    "title": "Importar desde Meta Tags",
                    "body": "Pega el bloque completo de etiquetas <strong>&lt;meta&gt;</strong> de un archivo de efecto antiguo a continuación. Esto sobrescribirá tu espacio de trabajo actual.",
                    "cancel": "Cancelar",
                    "importBtn": "Importar Efecto"
                },
                "share": {
                    "title": "Compartir tu Efecto",
                    "body": "Cualquiera con este enlace puede ver y cargar tu efecto.",
                    "copy": "Copiar"
                },
                "exportOptions": {
                    "title": "Exportar Propiedades",
                    "body": "Selecciona qué propiedades serán editables por los usuarios en SignalRGB. Las propiedades no marcadas se codificarán de forma rígida en el efecto.",
                    "cancel": "Cancelar",
                    "copyCode": "Copiar Código",
                    "generateZip": "Generar Archivo .zip",
                    "exposeAll": "Exponer Todo",
                    "hardcodeAll": "Codificar Todo",
                    "presets": "Preajustes:",
                    "presetAnimation": "Animación",
                    "presetColors": "Colores",
                    "presetGeometry": "Geometría",
                    "presetGradients": "Gradientes",
                    "presetMinimal": "Mínimo (Fácil)",
                    "presetStatic": "Estático (Sin Animación)"
                },
                "acceptTerms": {
                    "title": "Términos y Privacidad",
                    "body": "Al usar esta herramienta, aceptas los <a href=\"#\" data-bs-toggle=\"modal\" data-bs-target=\"#terms-modal\" data-bs-dismiss=\"modal\">Términos de Uso</a> y reconoces nuestra <a href=\"#\" data-bs-toggle=\"modal\" data-bs-target=\"#privacy-policy-modal\" data-bs-dismiss=\"modal\">Política de Privacidad</a>.",
                    "accept": "Acepto"
                },
                "copyProps": {
                    "title": "Copiar Propiedades",
                    "body": "Selecciona los grupos de propiedades que deseas copiar del objeto fuente.",
                    "cancel": "Cancelar",
                    "copyBtn": "Copiar al Portapapeles",
                    "pos": "Posición (X, Y)",
                    "size": "Tamaño (Ancho, Alto)",
                    "rot": "Rotación y Velocidad",
                    "fill": "Estilo de Relleno (Tipo, Colores, Gradiente)",
                    "anim": "Animación de Relleno (Modo, Velocidad, Dirección)",
                    "colAnim": "Animación de Color (Ciclo y Velocidad)",
                    "shape": "Tipo de Forma",
                    "shapeSpecific": "Propiedades Específicas de la Forma"
                },
                "pixelEditor": {
                    "title": "Editor de Pixel Art",
                    "width": "Ancho de Cuadrícula",
                    "height": "Alto de Cuadrícula",
                    "applySize": "Aplicar Nuevo Tamaño",
                    "tools": "Herramientas:",
                    "paint": "Pintar",
                    "fill": "Rellenar",
                    "flipH": "Voltear Horizontal",
                    "flipV": "Voltear Vertical",
                    "selectedFill": "Relleno Seleccionado",
                    "rawData": "Ver Datos Sin Procesar",
                    "jsonLabel": "Datos JSON (Avanzado)",
                    "cancel": "Cancelar",
                    "apply": "Aplicar Cambios"
                },
                "pasteSprite": {
                    "title": "Pegar Hoja de Sprites",
                    "body": "Introduce las dimensiones de un **cuadro único**. El código detectará automáticamente el número de filas y columnas en la hoja de sprites que pegues.",
                    "frameWidth": "Ancho de Cuadro Único",
                    "frameHeight": "Alto de Cuadro Único",
                    "downsample": "Reducir a dimensiones del cuadro (para pixel art de alta resolución)",
                    "append": "Añadir a cuadros existentes (en lugar de reemplazar)",
                    "pasteBtn": "Pegar desde Portapapeles"
                },
                "pixelGallery": {
                    "title": "Pixel Art de la Comunidad",
                    "searchPlaceholder": "Buscar por nombre de efecto o creador..."
                },
                "uploadGif": {
                    "title": "Opciones de Carga de GIF",
                    "body": "Especifica las dimensiones de pixel art objetivo para tu animación.",
                    "targetWidth": "Ancho Objetivo",
                    "targetHeight": "Alto Objetivo",
                    "maxColors": "Máx Colores (2-32)",
                    "reduceText": "Reduce la paleta del GIF al número especificado de colores.",
                    "append": "Añadir a cuadros existentes (en lugar de reemplazar)",
                    "originalInfo": "Info Original del GIF:",
                    "dims": "Dimensiones:",
                    "colors": "Colores Únicos:",
                    "process": "..."
                },
                "colorMapper": {
                    "title": "Mapear Colores",
                    "body": "Asigna los colores más comunes del primer cuadro a las ranuras disponibles en la paleta de tu objeto.",
                    "preview": "Vista Previa del Primer Cuadro",
                    "assignments": "Asignaciones de Color",
                    "cancel": "Cancelar",
                    "process": "Procesar Imagen"
                },
                "editColor": {
                    "title": "Editar Color",
                    "done": "Hecho"
                },
                "selectColor": {
                    "title": "Seleccionar Color"
                },
                "gifSearch": {
                    "title": "Buscar GIFs",
                    "placeholder": "Buscar GIFs...",
                    "search": "Buscar",
                    "close": "Cerrar"
                }
            },
            "gradientPicker": {
                "color": "Color:",
                "hex": "HEX",
                "position": "Posición:",
                "help": "<strong>Añadir:</strong> Clic en espacio vacío | <strong>Editar:</strong> Clic en input HEX o doble clic en marcador | <strong>Eliminar:</strong> Arrastrar marcador abajo"
            },
             "values": {
                "Rectangle": "Rectángulo",
                "Circle": "Círculo",
                "Ring": "Anillo",
                "Polygon": "Polígono",
                "Star": "Estrella",
                "Text": "Texto",
                "Oscilloscope": "Osciloscopio",
                "Tetris": "Tetris",
                "Fire": "Fuego",
                "Fire Radial": "Fuego Radial",
                "Pixel Art": "Pixel Art",
                "Audio Visualizer": "Visualizador de Audio",
                "Spawner": "Generador",
                "Strimer": "Strimer",
                "Polyline": "Polilínea",
                "Gif": "Gif",
                "Solid": "Sólido",
                "Linear": "Lineal",
                "Radial": "Radial",
                "Conic": "Cónico",
                "Alternating": "Alterno",
                "Random": "Aleatorio",
                "Rainbow": "Arcoíris",
                "Rainbow Radial": "Arcoíris Radial",
                "Rainbow Conic": "Arcoíris Cónico",
                "Cycle All Blocks": "Ciclar Todos los Bloques",
                "None": "Ninguno",
                "Loop": "Bucle",
                "Bounce": "Rebote",
                "Bounce Reversed": "Rebote Inverso",
                "Bounce Random": "Rebote Aleatorio",
                "Right": "Derecha",
                "Left": "Izquierda",
                "Up": "Arriba",
                "Down": "Abajo",
                "Small": "Pequeño",
                "Large": "Grande",
                "Center": "Centro",
                "Marquee": "Marquesina",
                "Typewriter": "Máquina de Escribir",
                "Wave": "Onda",
                "Flash": "Destello",
                "Volume Meter": "Medidor de Volumen",
                "Volume": "Volumen",
                "Bass": "Bajos",
                "Mids": "Medios",
                "Highs": "Agudos",
                "Sine": "Seno",
                "Square": "Cuadrada",
                "Sawtooth": "Diente de Sierra",
                "Triangle": "Triángulo",
                "Line": "Línea",
                "Points": "Puntos",
                "Both": "Ambos",
                "Bars": "Barras",
                "Area": "Área",
                "Circular": "Circular",
                "Sensor Meter": "Medidor de Sensor",
                "Time Plot": "Gráfico de Tiempo",
                "Cpu Load": "Carga de CPU",
                "Gpu Load": "Carga de GPU",
                "Ram Load": "Carga de RAM",
                "Net Down": "Descarga de Red",
                "Net Up": "Subida de Red",
                "Contain": "Contener",
                "Cover": "Cubrir",
                "Fill": "Rellenar",
                "Grayscale": "Escala de Grises",
                "Sepia": "Sepia",
                "Invert": "Invertir",
                "Blur": "Desenfocar",
                "Brightness": "Brillo",
                "Contrast": "Contraste",
                "Hue Rotate": "Rotar Matiz",
                "Saturate": "Saturar"
            }
        }
    }
};
